export const cities = [
  "Toronto, Ontario",
  "Montreal, Quebec",
  "Calgary, Alberta",
  "Ottawa, Ontario",
  "Edmonton, Alberta",
  "Mississauga, Ontario",
  "Winnipeg, Manitoba",
  "Vancouver, British Columbia",
  "Brampton, Ontario",
  "Hamilton, Ontario",
  "Quebec City, Quebec",
  "Surrey, British Columbia",
  "Halifax, Nova Scotia",
  "Laval, Quebec",
  "London, Ontario",
  "Markham, Ontario",
  "Vaughan, Ontario",
  "Gatineau, Quebec",
  "Saskatoon, Saskatchewan",
  "Kitchener, Ontario",
  "Longueuil, Quebec",
  "Burnaby, British Columbia",
  "Windsor, Ontario",
  "Regina, Saskatchewan",
  "Richmond, British Columbia",
  "Richmond Hill, Ontario",
  "Burlington, Ontario",
  "Oshawa, Ontario",
  "Sherbrooke, Quebec",
  "Greater Sudbury, Ontario",
  "Abbotsford, British Columbia",
  "Lévis, Quebec",
  "Coquitlam, British Columbia",
  "Barrie, Ontario",
  "Saguenay, Quebec",
  "Kelowna, British Columbia",
  "Guelph, Ontario",
  "Trois-Rivières, Quebec",
  "Whitby, Ontario",
  "Cambridge, Ontario",
  "St. Catharines, Ontario",
  "Milton, Ontario",
  "Langley, British Columbia",
  "Kingston, Ontario",
  "Ajax, Ontario",
  "Waterloo, Ontario",
  "Terrebonne, Quebec",
  "Saanich, British Columbia",
  "St. John's, Newfoundland and Labrador",
  "Thunder Bay, Ontario",
  "Delta, British Columbia",
  "Brantford, Ontario",
  "Saint John, New Brunswick",
  "Red Deer, Alberta",
  "Nanaimo, British Columbia",
  "Kamloops, British Columbia",
  "North Vancouver, British Columbia",
  "Chatham-Kent, Ontario",
  "Chilliwack, British Columbia",
  "Victoria, British Columbia",
  "Belleville, Ontario",
  "Sarnia, Ontario",
  "New Westminster, British Columbia",
  "Saint-Jérôme, Quebec",
  "Drummondville, Quebec",
  "Prince George, British Columbia",
  "Sherwood Park, Alberta",
  "Saint-Jean-sur-Richelieu, Quebec",
  "Fredericton, New Brunswick",
  "Saint-Jean, Quebec",
  "Penticton, British Columbia",
  "Sault Ste. Marie, Ontario",
  "Lethbridge, Alberta",
  "Terrebonne, Quebec",
  "Trois-Rivières, Quebec",
  "Prince Albert, Saskatchewan",
  "Grande Prairie, Alberta",
  "Wood Buffalo, Alberta",
  "Medicine Hat, Alberta",
  "Cape Breton, Nova Scotia",
];
